[package]
version = "0.7.0"
name = "helios-consensus-core"
edition = "2021"

[dependencies]
alloy = { version = "0.2.1", features = [
    "consensus",
    "rpc-types",
    "ssz",
    "rlp",
    "k256",
] }
alloy-rlp = "0.3.0"
bls12_381.workspace = true
ssz_types.workspace = true
ethereum_ssz_derive.workspace = true
ethereum_ssz.workspace = true
tree_hash_derive.workspace = true
tree_hash.workspace = true
typenum.workspace = true
sha2.workspace = true
eyre.workspace = true
serde.workspace = true
superstruct.workspace = true
thiserror.workspace = true
tracing.workspace = true
zduny-wasm-timer.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasmtimer = "0.2.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
snap = "1"
serde_yaml = "0.9.34"

# [patch.crates-io]
# ethereum_hashing = { git = "https://github.com/ncitron/ethereum_hashing", rev = "7ee70944ed4fabe301551da8c447e4f4ae5e6c35" }
# ssz_types = { path = "../ssz_types" }
# tree_hash = { path = "../tree_hash/tree_hash" }
# tree_hash_derive = { path = "../tree_hash/tree_hash_derive" }
# 
#[patch.crates-io]
#ssz_types = { git = "https://github.com/macladson/ssz_types", branch = "stable-container" }
#ethereum_ssz = { git = "https://github.com/macladson/ethereum_ssz", branch = "stable-container" }
#ethereum_ssz_derive = { git = "https://github.com/macladson/ethereum_ssz", branch = "stable-container" }
#tree_hash = { git = "https://github.com/macladson/tree_hash", branch = "stable-container" }
#tree_hash_derive = { git = "https://github.com/macladson/tree_hash", branch = "stable-container" }
